### ISSUE TITLE
Polish the Pixels 

### ISSUE THREAD

**Issue by AMS003010** [acmpesuecc/ArcList#1]
Elevate the UI with Sleek Designs to make it more user appealing 👁️
Please do use Tailwind CSS instead of Vanilla CSS

These might help
 - [Tailwind CSS](https://tailwindcss.com/)
 - [Dribbble](https://dribbble.com/) if you want some inspiration 😏

**Comment by Redslayer112** [comment]
Can I be assigned @Redslayer112 -> github username

**Comment by AMS003010** [comment]
!assign @Redslayer112

**Comment by AMS003010** [comment]
@Redslayer112 You will have 30 minutes to submit a PR to the issue

**Comment by AMS003010** [comment]
!deassign

**Comment by AMS003010** [comment]
!assign @Redslayer112 20

**Comment by AMS003010** [comment]
@Redslayer112  
You have been given an additional 20 minutes

**Comment by AMS003010** [comment]
Please send a screenshot once you are done

**Comment by Redslayer112** [comment]
![Uploading image.png…]()
finished issue...

**Comment by AMS003010** [comment]
!deassign
