### ISSUE TITLE
Smooth Moves

### ISSUE THREAD

**Issue by AMS003010** [acmpesuecc/ArcList#10]
✨ Get ready to take control of your todos! With drag & drop functionality, 🖱️ you can now easily reorder your tasks just the way you like. No more rigid lists—organize with a simple drag and drop 🎯.

Task: 🛠️ 
 - Implement drag & drop to let users rearrange their todos effortlessly. Let's make task management smoother and more fun!

**Comment by pratham-exe** [comment]
Can I get assigned to this ?

**Comment by AMS003010** [comment]
!assign @pratham-exe 90

**Comment by AMS003010** [comment]
@pratham-exe You can start working on this issue, if you want to
I will assign you later

**Comment by AMS003010** [comment]
@pratham-exe please pull and merge conflicts as a merge was just made

**Comment by AMS003010** [comment]
!assign @pratham-exe 50
