### ISSUE TITLE
Tune-Up

### ISSUE THREAD

**Issue by AMS003010** [acmpesuecc/ArcList#2]
Instructions
- Provide a new endpoint "/update" in the go backend to be able to modify the current Todo
- Use the new endpoint to modify a "Todo" on the frontend

**Comment by Son-0f-Anton** [comment]
can I be assigned

**Comment by AMS003010** [comment]
!assign @Anagha-Rao-53 90

**Comment by AMS003010** [comment]
@Anagha-Rao-53 You are already assigned an issue. A participant can work on only 1 issue at a time. Please do come back after you are done with your current issue.

**Comment by Son-0f-Anton** [comment]
i got deassigned cuz of the bot thing

**Comment by Son-0f-Anton** [comment]
!withdraw

**Comment by PandaTGOS** [comment]
Can I get assigned to this @AMS003010

**Comment by AMS003010** [comment]
@Anagha-Rao-53 Do you still want to work on this issue

**Comment by Son-0f-Anton** [comment]
Nope

**Comment by AdvaySanketi** [comment]
bro assign

**Comment by AMS003010** [comment]
!assign @AdvaySanketi 90

**Comment by AMS003010** [comment]
!assign @AdvaySanketi 90

**Comment by AMS003010** [comment]
!deassign

**Comment by AMS003010** [comment]
!aassign @AdvaySanketi 20

**Comment by AMS003010** [comment]
!assign @AdvaySanketi 20
