### ISSUE TITLE
Mission: Illuminate or Dim?

### ISSUE THREAD

**Issue by AMS003010** [acmpesuecc/ArcList#3]
You've been given a special quest! Your mission is to bring Dark Mode 🌆 to life for the frontend, where users can switch between the calming brightness of Light Mode and the sleek, midnight vibes of Dark Mode. ⚡️

Add a Dark Mode Toggle 🎛️ that lets users easily switch between these two styles. Bonus points if you add a smooth transition between modes! ✨

Are you up for the challenge? 💻🔧 Let the battle of light and shadow begin!

**Comment by sakshipai213** [comment]
please assign it to me

**Comment by AMS003010** [comment]
!assign @sakshipai213

**Comment by AMS003010** [comment]
@sakshipai213 You are already assigned an issue. A participant can work on only 1 issue at a time. Please do come back after you are done with your current issue.

**Comment by sakshipai213** [comment]
i am still...i just realised that i dont have go installed...

**Comment by sakshipai213** [comment]
im not able to do this..please unassign me.

**Comment by AMS003010** [comment]
!dessign

**Comment by AMS003010** [comment]
!deassign

**Comment by AMS003010** [comment]
@sakshipai213 You are not assigned to this issue

**Comment by Dhan1211** [comment]
can you assign this

**Comment by SavvyHex** [comment]
Can you please assign this to me?

**Comment by AMS003010** [comment]
!assign @Dhan1211

**Comment by AMS003010** [comment]
!assign @Dhan1211

**Comment by AMS003010** [comment]
@Dhan1211 You are already assigned an issue. A participant can work on only 1 issue at a time. Please do come back after you are done with your current issue.

**Comment by AMS003010** [comment]
!assign @SavvyHex

**Comment by AMS003010** [comment]
@SavvyHex 
You are still assigned in some other issue. I cannot assign you unless you are de-assigned

**Comment by Son-0f-Anton** [comment]
can i be assigned

**Comment by rachitraam** [comment]
Can i be assigned to this issue

**Comment by AMS003010** [comment]
!assign @Anagha-Rao-53 50

**Comment by AMS003010** [comment]
@Anagha-Rao-53 
Do you still want to work on it

**Comment by AMS003010** [comment]
!deassign

**Comment by AdvaySanketi** [comment]
Can you assign this issue to me please good sir

**Comment by AMS003010** [comment]
!assign @AdvaySanketi 50

**Comment by AyushChakraborty** [comment]
@AMS003010 please assign this to me

**Comment by sampada115** [comment]
can you assign it to me?

**Comment by sampada115** [comment]
@AMS003010

**Comment by AkshathaAcharya55555** [comment]
could i get assigned to this...

**Comment by AMS003010** [comment]
Sorry this issue is already assigned
