### ISSUE TITLE
Find It Fast

### ISSUE THREAD

**Issue by AMS003010** [acmpesuecc/ArcList#4]
✨ It's time to level up ArcList with a powerful search bar! 🔍 Say goodbye to endless scrolling—find your todos in a flash with just a few keystrokes.

🎯 Mission: Add a search bar that helps users swiftly find their todos from their ever-growing lists. 🚀 Let's make task management easier and faster!"

**Comment by atharv24mittal** [comment]
please assign it to me

**Comment by AMS003010** [comment]
!assign @atharv24mittal 50

**Comment by AMS003010** [comment]
You will have 50 minutes to complete the issue

**Comment by SanjoliT** [comment]
can i get assigned?

**Comment by AMS003010** [comment]
@SanjoliT The issue has already been assigned

**Comment by AMS003010** [comment]
@atharv24mittal  Do you still want to work on the issue as your time is up

**Comment by atharv24mittal** [comment]
@AMS003010 I think i have submitted it, can you please check

**Comment by AMS003010** [comment]
So shall I assign you again

**Comment by atharv24mittal** [comment]
yes

**Comment by AMS003010** [comment]
!deassign

**Comment by AMS003010** [comment]
!assign @atharv24mittal 45

**Comment by AMS003010** [comment]
@atharv24mittal Are you working on a different issue because a participant can work only on a single issue at a time

**Comment by Sarah-Kazi** [comment]
please assign it to me

**Comment by AMS003010** [comment]
!assign @Sarah-Kazi 50

**Comment by AMS003010** [comment]
@atharv24mittal You will have 50 minutes to make a PR to this isssue

**Comment by atharv24mittal** [comment]
@AMS003010 can you please chk the pr?

**Comment by AMS003010** [comment]
Make the PR to this issue please

**Comment by AMS003010** [comment]
@Sarah-Kazi 
Do you still want to work on it

**Comment by PandaTGOS** [comment]
Can I get assigned to this @AMS003010

**Comment by PandaTGOS** [comment]
Can I get assigned to this @AMS003010

**Comment by AMS003010** [comment]
!assign @PandaTGOS 50

**Comment by AMS003010** [comment]
@PandaTGOS 
You are already assigned an issue. A participant can work on only 1 issue at a time. Please do come back after you are done with your current issue.

**Comment by AMS003010** [comment]
@Sarah-Kazi 
Do you still want to work on it

**Comment by PandaTGOS** [comment]
> @PandaTGOS You are already assigned an issue. A participant can work on only 1 issue at a time. Please do come back after you are done with your current issue.

I am done with my previous issue it has been accepted as well
So am I still assigned to this ? @AMS003010

**Comment by AMS003010** [comment]
!assign @PandaTGOS 50

**Comment by AMS003010** [comment]
@PandaTGOS I am not able to assign you. Please check if you are still assigned some other issue

**Comment by PandaTGOS** [comment]
I have withdrawn from the previous one

**Comment by AMS003010** [comment]
!assign @PandaTGOS  50

**Comment by AMS003010** [comment]
!assign @PandaTGOS 50

**Comment by AMS003010** [comment]
!deassign

**Comment by AMS003010** [comment]
!assign @PandaTGOS 50

**Comment by AMS003010** [comment]
!assign @PandaTGOS 10

**Comment by AMS003010** [comment]
!assign @PandaTGOS 10

**Comment by AMS003010** [comment]
!deassign
